apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assignment1
  template:
    metadata:
      labels:
        app: assignment1
    spec:
      containers:
      - name: assignment1
        image: assignment1-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
