apiVersion: apps/v1
kind: Deployment
metadata:
  name: MLOpsAssignment1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MLOpsAssignment1
  template:
    metadata:
      labels:
        app: MLOpsAssignment1
    spec:
      containers:
      - name: MLOpsAssignment1
        image: MLOpsAssignment1-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
